tasks:
  - name: 卷 01 - 量子纠缠
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/01
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: ./dist/epub/卷 01 - 量子纠缠.epub
        id: tts-01
        title: 卷 01 - 量子纠缠
        creator: Hieronym
        publisher: rxliuli
        language: zh-CN
        cover: ./books/01/assets/cover.png
  - name: 卷 02 - 宇宙膨胀
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/02
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: ./dist/epub/卷 02 - 宇宙膨胀.epub
        id: tts-02
        title: 卷 02 - 宇宙膨胀
        creator: Hieronym
        publisher: rxliuli
        language: zh-CN
        cover: ./books/02/assets/cover.png
  - name: 卷 03 - 存在悖论
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/03
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: ./dist/epub/卷 03 - 存在悖论.epub
        id: tts-03
        title: 卷 03 - 存在悖论
        creator: Hieronym
        publisher: rxliuli
        language: zh-CN
        cover: ./books/03/assets/cover.png
  - name: 卷 04 - 爱因斯坦 - 罗森桥
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/04
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: ./dist/epub/卷 04 - 爱因斯坦 - 罗森桥.epub
        id: tts-04
        title: 卷 04 - 爱因斯坦 - 罗森桥
        creator: Hieronym
        publisher: rxliuli
        language: zh-CN
        cover: ./books/04/assets/cover.png
  - name: 番外
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/99
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: ./dist/epub/番外.epub
        id: tts-99
        title: 番外
        creator: Hieronym
        publisher: rxliuli
        language: zh-CN
        cover: ./books/99/assets/cover.png
